TWITTER_STREAMING_DATA_FILE = 'twitter_streaming_data.json'
MINUTES_GETTING_STREAM = 0.5
HOURS_PASSED_FOR_FILE_UPDATE = 2
NUMBER_DAYS_TO_FILE_REWRITE = 1
SECONDS_IN_MINUTE = 60
SECONDS_IN_HOUR = SECONDS_IN_MINUTE * 60
SECONDS_IN_DAY = SECONDS_IN_HOUR * 24
